services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freelance_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - freelance_network

  db:
    image: postgres:16-alpine
    container_name: freelance_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - freelance_network

  minio:
    image: minio/minio:latest
    container_name: freelance_minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"   
      - "9001:9001"   
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - freelance_network

volumes:
  postgres_data:
  minio_data:   

networks:
  freelance_network:
    name: freelance_network
    driver: bridge